### ISSUE TITLE
maxFiles prop not meant to allow additive selection?

### ISSUE THREAD

**Issue by kevinsmith** [harunhasdal/react-xhr-uploader#28]
I'm specifying `maxFiles={5}`, but it only allows multiple files if they're all selected and dropped at once (or selected at the same time using the browser's file picker). This is actually the same behavior I'm seeing on the [demo site](https://rma-consulting.github.io/react-xhr-uploader/) with the latest versions of both Chrome and Safari on macOS 10.12.6.

Is that the expected behavior? Given the name of the prop, I would've expected it to allow up to the given number of files even if they dragged in one at a time.

**Comment by harunhasdal** [comment]
Yes that is the expected behaviour. The idea is to use `maxFiles` for maximum number of files for one uploader operation and use multiple uploaders for multiple individual uploads (e.g. different field name for upload) if that is the usecase.
